apiVersion: v1
kind: Service
metadata:
  name: dictionary-api-service
  namespace: dictionary-api
  labels:
    app: dictionary-api
spec:
  type: ClusterIP
  selector:
    app: dictionary-api
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
