apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dictionary-api-ingress
  namespace: dictionary-api
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: dictionary-api.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: dictionary-api-service
            port:
              number: 80
