apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dictionary-api

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - mariadb-resources.yaml
  - mariadb-operator-instance.yaml
  - api-service.yaml
  - api-deployment.yaml
  - ingress.yaml

commonLabels:
  project: kubernetes-python-tasks
  version: "1.0.0"

commonAnnotations:
  managed-by: kubernetes
  created-date: "2026-01-15"
