apiVersion: k8s.mariadb.com/v1alpha1
kind: Database
metadata:
  name: dictionary-db
  namespace: dictionary-api
spec:
  mariaDbRef:
    name: mariadb-operator-instance
  characterSet: utf8mb4
  collate: utf8mb4_unicode_ci

---
apiVersion: k8s.mariadb.com/v1alpha1
kind: User
metadata:
  name: demo
  namespace: dictionary-api
spec:
  mariaDbRef:
    name: mariadb-operator-instance
  passwordSecretKeyRef:
    name: db-credentials
    key: mysql_password
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: Grant
metadata:
  name: demo-grant
  namespace: dictionary-api
spec:
  mariaDbRef:
    name: mariadb-operator-instance
  privileges:
    - "ALL PRIVILEGES"
  database: "dictionary-db"
  table: "*"
  username: "demo"