apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: dictionary-api
type: Opaque
stringData:
  database_url: "mysql+pymysql://demo:demo@mariadb-operator-instance.dictionary-api.svc.cluster.local:3306/dictionary-db"
  mysql_root_password: "demo"
  mysql_database: "dictionary-db"
  mysql_user: "demo"
  mysql_password: "demo"
