apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: dictionary-api
type: Opaque
stringData:
  database_url: "mysql://demo:demo@mariadb-service.dictionary-api.svc.cluster.local:3306/demo"
  mysql_root_password: "demo"
  mysql_database: "dictionary_db"
  mysql_user: "demo"
  mysql_password: "demo"
